export const sentences = [
    "The quick brown fox jumps over the lazy dog.",
  "Typing fast requires consistent daily practice.",
  "JavaScript can add interactivity to websites.",
  "Keep your fingers on the home row at all times.",
  "Accuracy is more important than raw speed.",
  "A watched pot never seems to boil.",
  "Coding is both art and logic combined.",
  "She sells seashells by the seashore.",
  "The sun rises in the east every morning.",
  "Practice makes permanent, not perfect.",
  "Pack my box with five dozen liquor jugs.",
  "I used to type slowly but now I’m faster.",
  "Short sentences help build momentum.",
  "Typing challenges can be fun and rewarding.",
  "A journey of a thousand miles begins with a single step.",
  "Never stop learning new skills every day.",
  "Real programmers write code, then test it.",
  "The dog barked loudly at the passing train.",
  "Each keystroke brings you closer to mastery.",
  "Learning to type is like learning to ride a bike.",
  "The keyboard is your gateway to creativity.",
  "Typing games improve muscle memory over time.",
  "Do not rush; let your hands find their rhythm.",
  "The lazy cat slept on the warm window sill.",
  "Every coder starts out as a beginner.",
  "Speed is great, but don’t sacrifice clarity.",
  "Errors are just stepping stones to success.",
  "Fast fingers are the result of focused effort.",
  "He typed the entire paragraph in one go.",
  "Great typists focus on rhythm and flow."
]